apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-kube-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-kube
  template:
    metadata:
      labels:
        app: nginx-kube
    spec:
      containers:
        - name: nginx-kube
          image: nginx:1.16
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
